project_id = "oyouhwcwkdcblioecduo"

[auth]
site_url = "https://flowsight-mvp.vercel.app"
additional_redirect_urls = ["https://flowsight-mvp.vercel.app/auth/confirm", "http://localhost:3000/auth/confirm", "http://localhost:3000/auth/confirm?next=/ops/cases"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email.template.magic_link]
subject = "Ihr Anmeldecode für den Leitstand"
content_path = "./supabase/templates/magic_link.html"
