// Stern 5 — Warmes Verkaufsgespräch — 1:1 aus
// docs/gtm/sales/stern5_warmes_verkaufsgespraech_uebergabe_cc.md (Version 1, eingefroren).
// Ziel: Zusage zum geführten Aufbau. Schweizer Hochdeutsch, Sie-Form, "echter Typ, kein Drücker".
// Final markierte Blöcke nicht umformulieren.

export interface WarmBlock { label?: string; text: string; }
export interface WarmPhase { key: string; title: string; blocks: WarmBlock[]; }

export const WARM_PHASES: WarmPhase[] = [
  {
    key: "opener",
    title: "1 · Warm-Opener / Sichtungsabgleich",
    blocks: [
      { label: "Opener", text: "Grüezi Herr [Name], Gunnar Wende aus Oberrieden.\n\nWir hatten ja vereinbart, dass ich mich nochmals kurz melde, nachdem ich Ihnen die Videoseite für [Betrieb] geschickt habe.\n\nErwische ich Sie gerade für zwei, drei Minuten — oder soll ich später nochmals anrufen?" },
      { label: "„Ja, passt gerade“", text: "Danke.\n\nHatten Sie schon kurz Gelegenheit, reinzuschauen?" },
      { label: "Spur A — gesehen", text: "Was war Ihr erster Gedanke, als Sie das gesehen haben?\n\n(Wenn knapp:) Hat es grundsätzlich einen Punkt getroffen — oder war es für Sie eher nicht relevant?" },
      { label: "Spur B — nicht gesehen", text: "Alles klar, danke für die offene Rückmeldung.\n\nDann würde ich es gar nicht am Telefon zerreden. Die Videoseite ist bewusst konkret für Ihren Betrieb vorbereitet — schauen Sie sie sich zuerst in Ruhe an.\n\nWann ist realistischer: soll ich mich morgen nochmals kurz melden oder eher übermorgen?" },
      { label: "Merksatz", text: "Hat er geschaut? → Eindruck holen. Hat er nicht geschaut? → nicht erklären, neuen Zeitpunkt setzen. (Keine Watch-Signale offenlegen.)" },
    ],
  },
  {
    key: "discovery",
    title: "2 · Discovery (Warm-Pfad ist Standard)",
    blocks: [
      { label: "Standard", text: "Video gesehen = der Aha ist passiert. Nicht bei null ausgraben (keine 6-Fragen-Liturgie): 1) offene Reaktion (oben) → 2) eine Konsequenzfrage (2.3) → 3) Drei-Monats-Bild (2.5) → Transition.\n\nEager-Buyer: sagt er „klingt gut, wie starten wir?“ — nicht durch Discovery zwingen. Fit kurz bestätigen → Preis → Aufbau." },
      { label: "2.3 Konsequenz", text: "Angenommen, einmal pro Woche bleibt irgendwo eine Kundenanfrage liegen oder läuft nicht sauber weiter — würden Sie das heute zuverlässig merken?\n\n(„Ja, würden wir merken“) Wie würden Sie es konkret merken — gibt es dafür einen festen Überblick, oder eher über Rückfragen, Telefonate und Erfahrung?\n\n(„Nein / nicht immer“) Genau das ist der Punkt. Dann geht es weniger um noch mehr Anfragen, sondern darum, dass der Betrieb jederzeit sieht, was offen ist und was weiterlaufen muss." },
      { label: "2.5 Drei-Monats-Bild", text: "Wenn wir drei Monate weiter wären und Sie sagen würden: Das hat sich für [Betrieb] gelohnt — woran würden Sie das im Alltag konkret merken?\n\n(Wenn er stockt:) Wäre es eher, dass weniger liegen bleibt — dass Sie als Chef mehr Überblick haben — oder dass Ihr Team weniger nachtelefonieren und nachfragen muss?" },
      { label: "Fallback 2.1 Realität", text: "Wenn bei Ihnen heute eine neue Kundenanfrage reinkommt — telefonisch, über Website, per E-Mail oder direkt aus einem Gespräch heraus — wie läuft das intern weiter?" },
      { label: "Fallback 2.2 Sichtbarkeit", text: "Und sehen Sie später auch die Anfragen, aus denen kein Auftrag geworden ist — oder vor allem die Fälle, die sauber durchgelaufen sind?" },
      { label: "Fallback 2.4 Wert", text: "Was wäre so eine Kundenanfrage bei Ihnen ungefähr wert, wenn daraus ein Auftrag wird?\n\n(„Kommt drauf an“) Nur grob: reden wir eher von ein paar hundert Franken, ein paar tausend — oder deutlich mehr?" },
    ],
  },
  {
    key: "transition",
    title: "3 · Transition / Brücke",
    blocks: [
      { label: "V6 Standard — Beat 1 (erden, Bestätigung holen)", text: "Okay — kurz, so wie Sie es gesagt haben: Der Punkt ist nicht, ob bei Ihnen sauber gearbeitet wird, sondern ob später sichtbar bleibt, was offen ist und was weiterlaufen muss.\n\nTrifft das?\n\n(Warten. Er muss bestätigen.)" },
      { label: "V6 — Beat 2 (mit seinem Erfolgsbild nach vorn)", text: "Und Sie haben vorhin gesagt, Sie würden es in drei Monaten daran merken, dass [sein konkretes Erfolgsbild].\n\nGenau dahin führt der nächste Schritt — und das ist kein grosses Projekt: Wir gehen Ihre Eingänge einmal gemeinsam durch und bauen daraus Ihr Leitsystem. Das meiste ist vorbereitet; die entscheidenden Punkte kommen aus Ihrem Betrieb.\n\nWollen wir kurz anschauen, wie das bei Ihnen konkret aussähe?" },
      { label: "V5 Fallback (weiche Discovery)", text: "Genau dafür war die Videoseite gedacht.\n\nDer nächste Schritt wäre kein grosses Projekt: Wir gehen Ihre Eingänge einmal gemeinsam durch und bauen daraus Ihr Leitsystem. Das meiste ist vorbereitet; die entscheidenden Punkte kommen aus Ihrem Betrieb.\n\nWollen wir kurz anschauen, wie das bei Ihnen konkret aussähe?" },
    ],
  },
  {
    key: "aufbau",
    title: "4 · Geführter Aufbau erklären",
    blocks: [
      { text: "Der geführte Aufbau heisst konkret:\n\nSie bekommen einen persönlichen Aufbau-Link. Dort gehen Sie Ihr Leitsystem Schritt für Schritt durch — angefangen bei Ihren Eingangskanälen wie Telefon, Website und direkten Gesprächen, bis hin zur Leitzentrale selbst.\n\nDas ist kein Formular und kein IT-Projekt. Sie klicken sich geführt durch Ihr eigenes System, bestätigen, was bereits vorbereitet ist, und ergänzen nur dort, wo Ihr Betrieb wirklich individuell ist.\n\nIn der Regel dauert das weniger als eine Stunde. Danach habe ich alles, was ich brauche, um Ihr Leitsystem sauber aufzusetzen und vor dem Go-live persönlich zu prüfen." },
    ],
  },
  {
    key: "preis",
    title: "5 · Preis-Choreografie",
    blocks: [
      { label: "Preis-Moment (eine Zahl, dann schweigen)", text: "Ja, dann müssen wir natürlich auch über den Preis sprechen.\n\nZur Einordnung: Wenn eine einzige gute Kundenanfrage liegen bleibt, reden wir bei Ihnen schnell über einen Auftrag im Wert von [seine Zahl / mehreren tausend Franken]. Und es geht nicht nur um diesen einen Auftrag, sondern um die Sicherheit, dass im Tagesgeschäft nichts mehr untergeht.\n\nBei Ihrer Betriebsgrösse liegt FlowSight bei rund [950 / 2'000] Franken im Monat, plus einmaligem Aufbau.\n\n[Hier endet dein Satz. Jetzt schweigst du — und sagst nichts mehr, bis er reagiert.]" },
      { label: "Erst NACH seiner Reaktion", text: "Dafür bekommen Sie Ihr Leitsystem für den Alltag: neue Kundenanfragen werden sauber aufgenommen, sichtbar weitergeführt und bis zum Abschluss nachvollziehbar. Und Sie zahlen nicht heute am Telefon, sondern erst, wenn Ihr System aufgebaut, geprüft und bereit für den Go-live ist." },
      { label: "Auf Rückfrage: einmaliger Aufbau", text: "Ja. Die Aktivierung liegt einmalig bei 2'500 Franken.\n\nDas ist der geführte Aufbau Ihres echten Systems: Eingänge durchgehen, Leitzentrale sauber aufsetzen, Lisa vorbereiten, alles prüfen und erst dann in den Go-live geben." },
    ],
  },
  {
    key: "abschluss",
    title: "6 · Abschluss nach Preis",
    blocks: [
      { label: "Favorit", text: "Wenn diese Grössenordnung für Sie grundsätzlich Sinn macht, wäre der nächste Schritt der geführte Aufbau.\n\nDann schicke ich Ihnen den persönlichen Aufbau-Link — wollen wir so starten?\n\n(Aufbau ist in Abschnitt 4 schon erklärt — hier NICHT erneut erklären, nur committen.)" },
      { label: "Weichere Alternative", text: "Wenn diese Grössenordnung für Sie grundsätzlich Sinn macht, würde ich als nächsten Schritt den geführten Aufbau starten.\n\nIch schicke Ihnen den persönlichen Aufbau-Link — wollen wir das so machen?" },
    ],
  },
  {
    key: "geparkt",
    title: "8 · Geparkt / Follow-up terminieren",
    blocks: [
      { text: "Verstehe ich. Dann würde ich es sauber parkieren, statt Sie jetzt zu drängen.\n\nNur damit ich es richtig einordne: Geht es eher um den Zeitpunkt — oder gibt es noch einen Punkt, der für Sie inhaltlich nicht klar ist?" },
      { label: "„Es ist der Zeitpunkt“", text: "Alles klar. Dann lassen Sie uns einen konkreten Zeitpunkt setzen, an dem es wieder realistisch ist. Dann müssen wir nicht lose im Raum bleiben.\n\nWas ist sinnvoller — in zwei Wochen nochmals kurz sprechen oder eher Anfang nächsten Monat?" },
      { label: "„Inhaltlich noch unklar“", text: "Verstehe ich. Dann sollten wir nicht einfach verschieben. Was ist der Punkt, der für Sie noch offen ist — Nutzen, Aufwand, Preis oder ob Ihr Team das im Alltag annimmt?" },
    ],
  },
  {
    key: "nein",
    title: "9 · Nein sauber beenden + Referral-Tür",
    blocks: [
      { text: "Verstehe ich. Dann ist es völlig in Ordnung, wenn wir es an dieser Stelle sauber lassen.\n\nMir ist lieber, Sie sagen klar Nein, als dass wir etwas aufbauen, das für [Betrieb] keinen echten Nutzen bringt.\n\nEine letzte Frage noch: Kennen Sie im Sanitär- oder Heizungsbereich einen Betrieb, bei dem genau dieses Thema — neue Kundenanfragen sauber aufnehmen und sichtbar weiterführen — eher ein Punkt sein könnte?" },
      { label: "Er nennt jemanden", text: "Danke, das hilft mir. Darf ich mich dort auf Sie beziehen — oder soll ich den Betrieb einfach neutral kontaktieren?" },
      { label: "Niemand", text: "Alles klar, kein Problem. Danke für das offene Gespräch, Herr [Name]. Ich wünsche Ihnen weiterhin gute Geschäfte." },
    ],
  },
];

// Einwand-Katalog 7.1–7.28 → Drill (Einwand → Antwort, aktiv abrufen).
export const WARM_DRILL: { cue: string; answer: string }[] = [
  { cue: "„Das ist viel / zu teuer.“", answer: "Verstehe ich. Die Zahl muss sich über den Alltag rechnen, nicht auf dem Papier.\n\nDeshalb würde ich es auch nicht schönreden: Wenn Ihr Leitsystem am Ende nur ein bisschen Ordnung schafft, reicht das nicht.\n\nDie Frage ist eher: Was müsste das Leitsystem für [Betrieb] konkret leisten, damit diese Grössenordnung für Sie Sinn macht?\n\n(Dann zurück zum Abschluss:) Wenn das der Massstab ist: Wollen wir den geführten Aufbau starten und genau darauf ausrichten?" },
  { cue: "„Warum ist das so teuer?“", answer: "Verstehe ich.\n\nDer Preis kommt nicht daher, dass da einfach eine App läuft. Der Preis kommt daher, dass Ihr Leitsystem im Alltag zuverlässig funktionieren muss: Kundenanfragen aufnehmen, sichtbar weiterführen, nichts liegen lassen und vor dem Go-live sauber geprüft werden.\n\nAm Ende ist die Frage nicht, ob es technisch viel kann. Die Frage ist: Gibt es Ihnen im Betrieb genug Sicherheit und Überblick, dass sich diese Grössenordnung rechnet?" },
  { cue: "„Warum ist das so günstig?“", answer: "Gute Frage.\n\nDer Preis ist bewusst so gesetzt, weil ich FlowSight gerade mit den ersten passenden Betrieben sauber aufbaue. Sie bekommen dadurch nicht weniger, sondern im Gegenteil: sehr direkte Nähe zu mir als Gründer und einen Aufbau, den ich persönlich prüfe.\n\nSpäter wird das wahrscheinlich standardisierter und weniger persönlich. In dieser Phase ist mir wichtiger, dass die ersten Betriebe wirklich sauber laufen.\n\nMacht das für Sie grundsätzlich Sinn?" },
  { cue: "„Ich muss es überlegen / mit Partner besprechen.“", answer: "Klar, das verstehe ich. Das ist kein Entscheid zwischen Tür und Angel.\n\nNur damit ich Sie richtig unterstütze: Was müsste für Sie oder intern noch klar sein, damit Sie sagen können, ob der geführte Aufbau Sinn macht?\n\n(„Muss es zeigen/besprechen“:) Dann besprechen Sie es intern in Ruhe, und wir setzen einen kurzen Zeitpunkt, an dem wir nochmals sprechen. Was ist realistischer — morgen oder Anfang nächster Woche?" },
  { cue: "„Können wir das zuerst testen?“", answer: "Ja, absolut verständlich. Ich würde an Ihrer Stelle auch nicht blind etwas starten wollen.\n\nDer Punkt ist: Wir machen keinen künstlichen Test mit einem leeren Demo-System. Sie bauen Ihr echtes Leitsystem geführt auf — mit Ihren Eingängen, Ihren Abläufen und Ihrer Leitzentrale.\n\nIhr Schutz ist: Sie zahlen nicht heute, sondern erst, wenn das System sauber aufgebaut, geprüft und bereit für den Go-live ist. Danach bleibt es monatlich kündbar.\n\nWäre das für Sie der richtige Rahmen, um es sauber zu prüfen?" },
  { cue: "„Wir haben schon ein System.“", answer: "Das ist gut — dann starten Sie nicht bei null.\n\nDie Frage ist eher: Deckt Ihr heutiges System wirklich den ganzen Weg ab — vom ersten Kontakt über Telefon, Website oder direktes Gespräch bis zur sichtbaren Weiterführung und zum sauberen Abschluss?\n\nWo würden Sie Ihr heutiges System da einordnen?" },
  { cue: "„Keine Zeit / ich bin kein IT-Mensch.“", answer: "Verstehe ich. Genau deshalb ist der Aufbau nicht als IT-Projekt gedacht.\n\nSie bekommen einen persönlichen Aufbau-Link und gehen Ihr Leitsystem Schritt für Schritt durch. Sie klicken sich geführt durch Ihre Eingangskanäle, bestätigen, was vorbereitet ist, und ergänzen nur dort, wo Ihr Betrieb individuell ist.\n\nIn der Regel dauert das weniger als eine Stunde. Den technischen Aufbau übernehme ich danach.\n\nWäre dieser Rahmen für Sie machbar?" },
  { cue: "„Unsere Kunden wollen nicht mit einer KI sprechen.“", answer: "Verstehe ich. Das wäre für mich auch eine rote Linie.\n\nLisa soll Ihre Kunden nicht „abfertigen“ und auch keinen Fachmann ersetzen. Sie nimmt sauber auf, worum es geht, fragt die wichtigsten Punkte ab und gibt die Anfrage strukturiert an Ihren Betrieb weiter.\n\nSie macht keine Preise, keine Diagnosen, keine verbindlichen Termine und keine Versprechen. Alles, was fachlich entschieden werden muss, bleibt bei Ihnen.\n\nDie Frage ist eher: Wenn ein Kunde niemanden erreicht, ist es dann besser, dass seine Anfrage sauber aufgenommen wird — oder dass er wartet, nochmals anruft oder zum nächsten Betrieb geht?" },
  { cue: "„Datenschutz? Wird das Gespräch aufgenommen?“", answer: "Gute Frage. Das ist wichtig.\n\nDie Gespräche werden nicht aufgenommen. Lisa nimmt nur die Informationen auf, die für die Anfrage nötig sind: Name, Kontakt, Anliegen, Dringlichkeit und die wichtigsten Angaben zum Fall.\n\nDie Daten werden sauber verarbeitet, die Server stehen in Frankfurt, und der Auftragsverarbeitungsvertrag ist Teil des Aufbaus.\n\nWäre es für Sie entscheidend, dass keine Gesprächsaufnahmen entstehen und trotzdem jede Anfrage sauber dokumentiert wird?" },
  { cue: "„Was, wenn Lisa etwas Falsches sagt?“", answer: "Verstehe ich. Genau deshalb darf Lisa bei uns nicht frei alles entscheiden.\n\nSie hat klare Grenzen: keine Preise, keine Diagnosen, keine verbindlichen Termine, keine Garantien. Wenn etwas fachlich unsicher ist, nimmt sie es sauber auf und gibt es an Ihren Betrieb weiter.\n\nDer Zweck ist nicht, den Fachmann zu ersetzen. Der Zweck ist, dass keine Anfrage verloren geht und Sie später strukturiert sehen, worum es geht.\n\nWäre das für Sie die richtige Grenze?" },
  { cue: "„Läuft das schon bei mir? / Ist das schon aktiv?“", answer: "Gute Frage.\n\nNein, live ist es bei Ihnen noch nicht. Was Sie gesehen haben, ist die vorbereitete Sicht darauf, wie Ihr Leitsystem für [Betrieb] aussehen und funktionieren soll.\n\nLive wird es erst nach dem geführten Aufbau: Sie gehen Ihre Eingänge durch, ich setze das System sauber auf, prüfe es vor dem Go-live — und erst dann wird es auf echte Anfragen geschaltet.\n\nWichtig ist mir, dass wir hier nichts halb live nehmen. Erst sauber aufbauen, dann live gehen." },
  { cue: "„Kann ich meine Nummer behalten? / Wie läuft das mit dem Telefon?“", answer: "Ja, Ihre bestehende Nummer bleibt die Nummer, die Ihre Kunden kennen.\n\nIm Aufbau klären wir sauber, wie Anrufe künftig weiterlaufen sollen: wann Lisa übernimmt, wann direkt zu Ihnen oder ins Büro weitergeleitet wird und was bei Notfällen oder dringenden Fällen passiert.\n\nDas wird nicht einfach blind umgestellt. Erst wird es sauber eingerichtet und geprüft, dann gehen wir live." },
  { cue: "„Wir sind schon mal bei einer Agentur reingefallen.“", answer: "Verstehe ich. Dann wäre ich an Ihrer Stelle auch vorsichtig.\n\nGenau deshalb ist der Ablauf so aufgebaut, dass Sie nicht blind etwas kaufen: Sie sehen zuerst die Videoseite, dann gehen Sie den geführten Aufbau durch, und gezahlt wird erst, wenn Ihr Leitsystem sauber aufgebaut, geprüft und bereit für den Go-live ist.\n\nMir ist wichtig, dass Sie vor dem Start wissen, was Sie bekommen — und dass nichts einfach versprochen wird, was im Alltag nachher nicht hält.\n\nWas wäre für Sie wichtig, damit sich das diesmal sauber und verlässlich anfühlt?" },
  { cue: "„Mein Büro / meine Frau macht das schon.“", answer: "Das ist gut — dann ist bei Ihnen bereits jemand verantwortlich.\n\nMir geht es auch nicht darum, diese Arbeit zu ersetzen. Die Frage ist eher: Sieht Ihr Betrieb später sauber, was alles reingekommen ist, was offen ist und was weiterlaufen muss — unabhängig davon, ob es über Telefon, Website oder direkt aus einem Gespräch kam?\n\nWenn ja, ist das sauber gelöst. Wenn nein, wäre genau dort der Nutzen des Leitsystems." },
  { cue: "„Schauen wir später an / nach den Ferien.“", answer: "Verstehe ich. Man muss nicht alles sofort entscheiden.\n\nDie Frage ist nur: Was glauben Sie, ändert sich bis dahin an dem Thema? Wenn neue Kundenanfragen heute schon über mehrere Wege reinkommen, wird es im Herbst wahrscheinlich nicht weniger relevant.\n\nWenn es grundsätzlich kein Thema ist, ist das völlig in Ordnung. Wenn es aber ein Thema ist, würde ich es nicht künstlich liegen lassen.\n\nWollen wir es lieber sauber parkieren — oder den geführten Aufbau jetzt schlank starten?" },
  { cue: "„Ich muss zuerst mein Team fragen.“", answer: "Verstehe ich. Das ist wichtig.\n\nWenn Ihr Team das Gefühl hat, es kommt einfach noch ein System obendrauf, dann wird es nicht funktionieren. Der Aufbau muss so gemacht sein, dass es im Alltag einfacher wird: weniger Nachfragen, weniger Suchen, klarer sehen, was offen ist und was weiterlaufen muss.\n\nGenau deshalb gehen wir im geführten Aufbau auch durch, wer was sehen muss und wie es bei [Betrieb] wirklich läuft.\n\nWas wäre aus Ihrer Sicht der Punkt, an dem Ihr Team am ehesten sagen würde: Das hilft uns tatsächlich?" },
  { cue: "„Wer betreut das nach dem Go-live?“", answer: "Gute Frage.\n\nNach dem Go-live lassen wir das nicht einfach laufen und verschwinden. Gerade am Anfang schaue ich mit drauf, ob die ersten echten Anfragen sauber reinkommen, ob die Abläufe passen und ob irgendwo nachjustiert werden muss.\n\nWichtig ist: Das Leitsystem muss im Alltag funktionieren, nicht nur im Aufbau gut aussehen.\n\nWenn etwas nicht sauber läuft, wird es angepasst — genau deshalb gibt es den geprüften Go-live und die Begleitung danach." },
  { cue: "„Gibt es eine Mindestlaufzeit?“", answer: "Nein, es gibt keine lange Mindestlaufzeit.\n\nNach dem Go-live läuft der Monatsbetrieb monatlich kündbar. Das ist bewusst so, weil das Leitsystem im Alltag Nutzen bringen muss — nicht nur im Verkaufsgespräch gut klingen darf.\n\nWenn es für [Betrieb] keinen konkreten Nutzen bringt, möchte ich Sie nicht in einen langen Vertrag drücken." },
  { cue: "„Was passiert mit Bewertungen?“", answer: "Gute Frage.\n\nDie Bewertungsfunktion ist nicht dafür gedacht, Kunden künstlich zu drängen. Der Punkt ist: Wenn ein Auftrag sauber abgeschlossen ist und der Kunde zufrieden ist, kann genau im richtigen Moment eine Bewertungsanfrage ausgelöst werden.\n\nDas hilft, weil zufriedene Kunden sonst oft einfach weitergehen — und nur die Unzufriedenen von selbst laut werden.\n\nWichtig ist: Erst muss der Fall sauber abgeschlossen sein. Dann kann eine Bewertung sinnvoll angestossen werden." },
  { cue: "„Brauchen wir das wirklich? / Übertrieben für uns?“", answer: "Verstehe ich. Genau diese Frage sollten Sie stellen.\n\nFür mich ist der Massstab nicht, ob [Betrieb] „mehr Digitalisierung“ braucht. Der Massstab ist einfacher: Kommen heute genug Kundenanfragen über verschiedene Wege rein, dass Sichtbarkeit im Alltag einen echten Nutzen bringt?\n\nWenn die Antwort nein ist, brauchen Sie es nicht. Wenn die Antwort ja ist, dann geht es nicht um etwas Übertriebenes — sondern darum, dass nichts Wichtiges im Tagesgeschäft untergeht." },
  { cue: "„Warum nicht einfach intern lösen?“", answer: "Das können Sie grundsätzlich natürlich.\n\nDie Frage ist eher, ob es intern wirklich als durchgängiges Leitsystem entsteht — vom ersten Kontakt über die sichtbare Weiterführung bis zum sauberen Abschluss — oder ob am Ende wieder einzelne Listen, Notizen, Telefonate und Absprachen nebeneinanderlaufen.\n\nMein Punkt ist: Ich habe genau diesen Ablauf für Betriebe wie Ihren vorbereitet, damit Sie nicht bei null anfangen. Wo sehen Sie das grössere Risiko — selbst aufbauen oder einen fertigen Ablauf übernehmen?" },
  { cue: "„Können Sie mir das schriftlich schicken?“", answer: "Ja, natürlich.\n\nIch schicke Ihnen gerne kurz schriftlich zusammen, was wir besprochen haben: was das Leitsystem bei [Betrieb] leisten soll, wie der geführte Aufbau abläuft und welche Grössenordnung gilt.\n\nMir wäre nur wichtig, dass es nicht bei allgemeinen Unterlagen bleibt. Der entscheidende Punkt ist ja Ihr konkreter Betrieb — und genau dafür ist die Videoseite und der Aufbau gedacht.\n\nSoll ich Ihnen die kurze Zusammenfassung per Mail schicken und wir halten direkt einen Zeitpunkt fest, an dem wir es nochmals sauber einordnen?" },
  { cue: "„Wie schnell wäre das live?“", answer: "Wenn Sie den geführten Aufbau zügig durchgehen, können wir relativ schnell startklar sein.\n\nDer Ablauf ist: Sie gehen Ihr Leitsystem über den Aufbau-Link Schritt für Schritt durch. Danach setze ich es sauber auf, prüfe es persönlich und erst wenn alles passt, gehen wir live.\n\nMir ist wichtiger, dass es sauber live geht, als dass wir es künstlich schnell schalten. Realistisch sprechen wir eher von wenigen Tagen als von Wochen — vorausgesetzt, die Informationen aus dem Aufbau sind vollständig." },
  { cue: "„Was brauchen Sie konkret von mir?“", answer: "Nicht viel — aber die richtigen Dinge.\n\nSie gehen über den persönlichen Aufbau-Link Schritt für Schritt durch Ihr Leitsystem. Dort klären wir zum Beispiel: Welche Eingänge sind wichtig, wer im Betrieb was sehen muss, wie dringende Fälle behandelt werden und wie ein Fall bei Ihnen sauber abgeschlossen ist.\n\nDas meiste ist vorbereitet. Von Ihnen brauche ich vor allem die Betriebslogik, die niemand von aussen wissen kann.\n\nIn der Regel ist das in weniger als einer Stunde erledigt." },
  { cue: "„Was, wenn Kunden trotzdem direkt bei mir anrufen?“", answer: "Das wird weiterhin passieren — und das ist auch in Ordnung.\n\nFlowSight soll nicht verhindern, dass Kunden Sie direkt erreichen. Der Punkt ist eher: Wenn aus so einem direkten Gespräch eine Kundenanfrage entsteht, sollte sie danach nicht nur im Kopf oder auf einem Zettel bleiben, sondern sauber im Leitsystem sichtbar werden.\n\nGenau deshalb sind direkte Gespräche im Aufbau mit drin. Wir klären, wie solche Anfragen bei [Betrieb] aufgenommen werden, damit sie später nicht untergehen." },
  { cue: "„Wer sieht die Anfragen im Betrieb?“", answer: "Das legen wir im geführten Aufbau sauber fest.\n\nNicht jeder muss alles sehen. Entscheidend ist, dass die richtigen Personen im Betrieb sehen, was für sie relevant ist: offene Anfragen, laufende Fälle, dringende Themen und abgeschlossene Arbeiten.\n\nFür Sie als Inhaber geht es vor allem darum, jederzeit den Überblick zu haben, ohne jedem einzelnen Fall hinterherlaufen zu müssen.\n\nWie das bei [Betrieb] genau aufgeteilt wird, klären wir im Aufbau." },
  { cue: "„Warum gerade jetzt mit Ihnen, wo Sie noch am Anfang stehen?“", answer: "Gute Frage. Ich bin damit bewusst noch früh unterwegs.\n\nDer Vorteil für Sie ist: Sie bekommen kein anonymes Standardprodukt, sondern einen Aufbau, bei dem ich persönlich hinschaue, ob das Leitsystem für [Betrieb] im Alltag wirklich Sinn macht.\n\nIch werde Ihnen auch nichts verkaufen, wenn ich merke, dass es für Ihren Betrieb nicht passt. Aber wenn es passt, sind Sie einer der ersten Betriebe, bei denen das sehr nah und sauber aufgebaut wird.\n\nIst Ihnen in dieser Phase persönliche Nähe und saubere Umsetzung wichtiger — oder wäre Ihnen ein etablierter Anbieter mit mehr Referenzen lieber?" },
  { cue: "„Was sagt Lisa dem Kunden, wann jemand kommt?“", answer: "Gute Frage — und genau da ist sie bewusst zurückhaltend.\n\nLisa sagt nie einen fixen Termin zu. Sie setzt nur die Erwartung, die wir vorher mit Ihnen festlegen — zum Beispiel: „Ein Mitarbeiter meldet sich so rasch er kann und bestätigt Ihnen einen Termin.“ Und sie nimmt die Wunschzeiten und die Dringlichkeit des Kunden sauber auf.\n\nSo weiss Ihr Techniker beim Rückruf schon, wann es dem Kunden passt — und der Kunde hat das Gefühl, dass seine Anfrage ernst genommen wird, statt im Nichts zu landen.\n\nWie verbindlich das sein soll, legen wir im Aufbau gemeinsam fest — je nachdem, wie schnell Sie zuverlässig zurückrufen können." },
];
